### ISSUE TITLE
[v1.0.0-rc.1 - fixed in offcial release] UI: Progress bar cropped when using a higher display scale

### ISSUE THREAD

**Issue by LarsJandel** [DotBow/Blender-Launcher#1]
**Describe the bug**
I am using a high res display having the scale set to 150%. Everything looks fine in the UI except for the progress bar, which gets cropped a little bit.

**To Reproduce**
1. Windows 10: Go to Settings/Display: Scale and layout
2. Set Scale to e.g. 150%
3. The progress bar will be cropped

**Expected behavior**
The progress bar not being cropped like when using a scale of 100%.

**Screenshots**
As a comparison, a screenshot while using 150% and 100% display scale.
![DisplayScale-150pct](https://user-images.githubusercontent.com/32457827/82864505-f8cc5080-9f24-11ea-849f-c7d4316e305f.png)
![DisplayScale-100pct](https://user-images.githubusercontent.com/32457827/82864524-008bf500-9f25-11ea-8f88-bcae3b723ecf.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: v1.0.0-rc.1

**Additional context**
Just a minor cosmetic issue. Fantastic app - thanks! 😊

**Comment by DotBow** [comment]
Hi! Thanx for report!
I can't reproduce error on my side. You should keep in mind that changing DPI or scale **won't scale** all layouts properly - application should be **restarted** to adapt (or at least minimize to tray icon and back to force everything redraw). That's how it looks to me with 150% scale:
![изображение](https://user-images.githubusercontent.com/32243930/82869348-c6c3ea00-9f36-11ea-8b13-ae611aeca0a7.png)
But you also have a bigger resolution on top of scaling, so that's might be an issue.
I will dive into issue asap anyway 😉
Please give me know if issue is solved by restarting app because right now it is not adapting properly.

**Comment by LarsJandel** [comment]
Well, 150% is my standard scale - only tried 100% without restarting. So, the issue persists when starting the app again. Thanks for your quick response.
Tried with a lower resolution and 150% - same issue... 🤔
![DisplayScale-150pct-lowerRes](https://user-images.githubusercontent.com/32457827/82871253-93cb2780-9f31-11ea-9989-4d1113b0e542.png)

**Comment by LarsJandel** [comment]
Additional note - maybe related:
The default launch size of the window is quite small - doesn't fit the content without manual resizing. Thanks.
![Blender Launcher 2020-05-26 09 21 07](https://user-images.githubusercontent.com/32457827/82871829-6fbc1600-9f32-11ea-81ac-c44bf5ffe6cb.png)

**Comment by LarsJandel** [comment]
...ah, wait - I am afraid, I didn't use the latest version. I am so sorry - this issue doesn't exist. Everything is larger. Progress bar not cropped. Well, I noted rc1 myself, wrong one in my download folder. The latest official one looks all good. Sorry...
![Blender Launcher 2020-05-26 09 53 07](https://user-images.githubusercontent.com/32457827/82875006-19050b00-9f37-11ea-807b-78262493dbee.png)

**Comment by DotBow** [comment]
Oh, sorry, missed that the rc-1 was in your comment, glad new one works perfect! 
I appreciate report anyway! 💖
