### ISSUE TITLE
Drag and drop impossible

### ISSUE THREAD

**Issue by shadkp** [DotBow/Blender-Launcher#156]
Hello, I've come accross a small issue... It is apparently impossible to drag and drop to blender, when starting from blender launcher.

**Comment by PCMonsterx** [comment]
I believe this issue is still open.

If so I am having the same problem. I am not able to drag image files into any sub-screens within Blender. I Have to use the Blender folder icons to open the internal file browser and navigate to my images. I am able to drag from the internal file browser to the Shading window to places images etc.. but nothing from windows file explorer.

I have Blender Launcher stored on my C drive in Program Files and had to allow run as admin to be able to download from the launcher. Not sure if that would apply but those are the only "Special" changes from the "out of the box" Blender Launcher.

**Comment by PCMonsterx** [comment]
> I believe this issue is still open.
> 
> If so I am having the same problem. I am not able to drag image files into any sub-screens within Blender. I Have to use the Blender folder icons to open the internal file browser and navigate to my images. I am able to drag from the internal file browser to the Shading window to places images etc.. but nothing from windows file explorer.
> 
> I have Blender Launcher stored on my C drive in Program Files and had to allow run as admin to be able to download from the launcher. Not sure if that would apply but those are the only "Special" changes from the "out of the box" Blender Launcher.

I moved the Blender Launcher and the Blender builds to a different Drive and removed the "run as Admin" property. I am able to download new builds and Drag & Drop files into Blendr again. Hope this helps for the future!
