### ISSUE TITLE
Blender Launcher crashes during launch with: "Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'" 

### ISSUE THREAD

**Issue by johnyc90** [DotBow/Blender-Launcher#174]
**Describe the bug**
Blender Launcher is failing to launch on a freshly installed Fedora36.

**To Reproduce**
1. Download the executable.
2. Launch it.

**Expected behavior**
The executable doesn't launch. A complete log is provided, but there isn't any other important detail besides the message listed in this bug title. 

**System (please complete the following information):**
 - Operation system: Fedora36
 - Blender Launcher version: v1.15.0 to 1.14.0
 - Log file: [crash.log](https://github.com/DotBow/Blender-Launcher/files/9288047/crash.log)

**Comment by DotBow** [comment]
Hi!

Please, try to use a [command line to setup a Library Folder ](https://dotbow.github.io/Blender-Launcher/library_folder/#changing-library-folder)

Or check if this workaround helps #103

**Comment by johnyc90** [comment]
Hello @DotBow,

Neither seems to solve the issue. It still crashes with the same error.
I'll try building from source and check for any dependencies.

**Comment by Jet-2** [comment]
So a bit late to the issue but it might still help: try adding ```GDK_BACKEND=x11``` in front of the startup command so like 
```GDK_BACKEND=x11 ./BlenderLauncher```. 
(you nevertheless still need to set the library folder in the args)

Also from what I know the xsettings antialiasing issue is only when using wayland on newer gnome because old gtk application aspect the gtk key wich got removed in gtk4. So I guess somewhere in the BlenderLauncher is an outdated library using something under gtk3 but im not sure @DotBow maybe you can check if there are any updates. Nevertheless the GDK_BACKEND fix should work when you are using Wayland (also its only application based so you'll keep all benefits of wayland).
Hope we can close that issue and all other issues about xsettings.

**Comment by johnyc90** [comment]
Thanks for the tip @Jet-2. This actually brought a new error message:
`Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "windows/main_window.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[15874] Failed to execute script 'main' due to unhandled exception!
`
But switching back to xorg solves the issue. Wayland is not must right now so I can live with it.

**Comment by Jet-2** [comment]
Well for me it worked on Fedora 36 and Wayland, however now it also broke again after upgrading to Fedora 37 and because of some unrelated issues I also switched back to x11
