### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by JimmyShrimp** [DotBow/Blender-Launcher#178]
**Is your feature request related to a problem? Please describe.**
Firstly, the product is great, thanks!
I just have an ongoing issue with versions where I need to remember what addon works with what version etc.

**Describe the solution you'd like**
I would personally find it very useful to have a notes field within the 'Library' tab.
I have a few addons that work with specific versions of Blender, A notes field would help me keep track of this.

**Describe alternatives you've considered**
None as this would need to take place within Blender Launcher

**Additional context**
Example: Lets say I have an addon called 'CAD Tools' that only works with Blender 2.8 - the end result would be a column that displayed this data, or a section of the data or an option to display additional info by right click menu or clicking on an indicator showing that there is more data.

Apologies if none of that makes any sense!

**Comment by xan2622** [comment]
Hi JimmyShrimp.

Alternatively, here is what you can do: 

1. Make your Blender installation(s) portable: [#116](https://github.com/DotBow/Blender-Launcher/issues/116)
2. Customize the Blender Interface the way you like (but on the Layout workspace, open the Text Editor in a new area)
3. In that Text Editor, create a new file and type a list of add-ons that work with that Blender version
4. Go to the menu `File > Defaults > Save Startup File` 
5. Save Preferences and restart Blender

![Capture d’écran 2022-08-16 131340](https://user-images.githubusercontent.com/1732773/184868969-8743d4ce-ae12-4460-b7d8-c26edc5b63f6.png)

If you do that for all your Blender instances, that should help you know which add-ons are compatible with each Blender version.

**Comment by JimmyShrimp** [comment]
Hi, thanks for the response. 

Do I assume that I would need to open Blender to view this info?

The idea was to move the info to Blender-launcher  so that I can view the info prior to launching Blender.

I Appreciate the info though I will try it out.

Thanks

**Comment by xan2622** [comment]
Yes, this "workaround" requires you to open Blender to view this info.

---

Here is a possible implementation for your idea: 

1. The _right-click menu_ could have a new entry: "Write Custom Notes"

<img src="https://user-images.githubusercontent.com/1732773/184945829-64b96bd5-8a7d-4821-a31b-6152507bf99c.png" width="50%" height="50%">

2. Clicking on it would create (in the background) a text file in the _builds downloads folder_ (the filename would start with the version number and would end with "_CustomNotes.txt") : 

<img src="https://user-images.githubusercontent.com/1732773/184941362-1811c5ca-6e56-44d5-a54a-69fbf6731860.png" width="75%" height="75%">

3.  ... then this text file would immediately open for edition:   

<img src="https://user-images.githubusercontent.com/1732773/184943232-49e3f59f-8e90-4a24-8c76-79f2a7ffcc72.png" width="50%" height="50%">

4. Once you have finished editing the text file, you save it and close the text editor.

5. Blender Launcher detects that a "CustomNotes" text file has been created and now allows you to show these "CustomNotes" with the "Read Custom Notes" entry:

<img src="https://user-images.githubusercontent.com/1732773/184945916-8c72abe4-0bda-4963-84f8-4906eecc73ac.png" width="50%" height="50%">

6. Here is what the UI could look like (with a built-in text viewer): 

<img src="https://user-images.githubusercontent.com/1732773/184953775-b95b14e5-e53d-4991-86af-0ce570f59c8a.png" width="75%" height="75%">

This is just an idea of implementation. DotBow certainly knows a better way.

**Comment by xan2622** [comment]
Yes, this "workaround" requires you to open Blender to view this info.

---

Here is a possible implementation for your idea: 

1. The _right-click menu_ could have a new entry: "Write Custom Notes"

<img src="https://user-images.githubusercontent.com/1732773/184945829-64b96bd5-8a7d-4821-a31b-6152507bf99c.png" width="50%" height="50%">

2. Clicking on it would create (in the background) a text file in the _builds folder_ (the filename would start with the version number and would end with "_CustomNotes.txt") : 

<img src="https://user-images.githubusercontent.com/1732773/184941362-1811c5ca-6e56-44d5-a54a-69fbf6731860.png" width="75%" height="75%">

3.  ... then this text file would immediately open for edition:   

<img src="https://user-images.githubusercontent.com/1732773/184967220-ce09b708-71be-4e2a-bcf6-00048c1651b0.png" width="50%" height="50%">

4. Once you have finished editing the text file, you save it and close the text editor.

5. Blender Launcher detects that a "CustomNotes" text file has been created and now allows you to show these "CustomNotes" with the "Read Custom Notes" entry:

<img src="https://user-images.githubusercontent.com/1732773/184945916-8c72abe4-0bda-4963-84f8-4906eecc73ac.png" width="50%" height="50%">

6. Here is what the UI could look like (with a built-in text viewer): 

<img src="https://user-images.githubusercontent.com/1732773/184967423-6680f3d4-7536-4ccb-ba47-8e1dc6a51350.png" width="75%" height="75%">

This is just an idea of implementation. DotBow certainly knows a better way.


EDIT: now that I am thinking about it.. *custom notes (text) files* would need to be editable afterwards.. at any time.. and within Blender Launcher itself (otherwise the user would have to browse the builds folders to find the text files prior to re-edit them later..)
That's why maybe, this text viewer on the right side (on my mock-up image above) would rather need to be a (basic) text editor instead.

**Comment by JimmyShrimp** [comment]
That looks great and more of what I was thinking.

I use Blender Launcher all the time now as it makes life easier and I was just thinking about how many different versions of Blender I carry, why and how can I make it easier to see what does what.

Another example would be a user adding notes to self warning of any bugs / crashes / risks in the version they are opening.

Of course, all of this is subject to whether you see any benefit in development or not.

Either way, its a great product!

**Comment by xan2622** [comment]
> Another example would be a user adding notes to self warning of any bugs / crashes / risks in the version they are opening.

The Built-in text editor could be also useful for Add-ons Developers : it could help them write notes about their add-ons according to each Blender version.

**Comment by JimmyShrimp** [comment]
The more you look at it, the handier it becomes!

**Comment by xan2622** [comment]
Another mock-up : (this one is probably simpler to implement as it is a simple "window", rather than a panel inside the main UI of Blender Launcher, like in my previous mock-up)

![5620](https://user-images.githubusercontent.com/1732773/185124264-a63ea134-8de8-44c2-bb11-8946311374ec.png)

The Text Editor (shown in the window above) would follow the movement of the main Blender Launcher UI (just like the Settings window which position is stuck).

**Comment by JimmyShrimp** [comment]
Would there be a notifier on the main window that would highlight you to notes being recorded next to each library entry?

**Comment by JimmyShrimp** [comment]
Perfect! :)

**Comment by xan2622** [comment]
Now, let's hope DotBow likes this idea too.  🤞

**Comment by JimmyShrimp** [comment]
I take it this wont get looked at?

**Comment by xan2622** [comment]
I hope it will.
DotBow hasn't given any news for weeks (no new commit nor reply). I hope everything's fine (afaik, DotBow lives in Russia...).

**Comment by JimmyShrimp** [comment]
Blimey, I hope DotBow is ok, no matter what your politics are that's not a good place to be at the moment.

**Comment by JimmyShrimp** [comment]
Blimey, I hope DotBow is ok.  Things are more than a little weird across the planet right now. From: xan2622Sent: 09 October 2022 04:15To: DotBow/Blender-LauncherCc: JimmyShrimp; AuthorSubject: Re: [DotBow/Blender-Launcher] Notes field (Issue #178) I hope it will.DotBow hasn't given any news for weeks (no new commit nor reply). I hope everything's fine (afaik, DotBow lives in Russia..).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by xan2622** [comment]
@JimmyShrimp I think you replied from your email but it's always better to leave a comment directly on Github, after logging in. :)

You can edit or delete your previous comment if you want (here on Github).
