### ISSUE TITLE
quick launch Global shortcut does not work

### ISSUE THREAD

**Issue by baronlanteigne** [DotBow/Blender-Launcher#181]
**Describe the bug**
quick launch Global shortcut does not work for me.

**To Reproduce**
I tried changing the shortcut. I made sure a blender install was set as quick launch.

It used to work in previous versions... I was addicted to this shortcut!

**System (please complete the following information):**

windows 10 pro 19043
Blender_Launcher_v1.15.1_Windows_x64

**Comment by DotBow** [comment]
Hi!

Please, try this build:
https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477 

Although F* keys seems to not work

**Comment by baronlanteigne** [comment]
Oh that's it! Thank you!

**Comment by L0Lock** [comment]
Hi!

Just pointing out that I also have the issue, my middle-mouse-button quicklaunch stopped working at some point, it opens the launcher instead of Blender.  
I updated to [#163 dev version](https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477) a while ago because of v1.15 crashes but it didn't fix the issue so far.

Now the build seem to be impossible to download anyway.
