### ISSUE TITLE
Frequent crashes when in background?

### ISSUE THREAD

**Issue by baronlanteigne** [DotBow/Blender-Launcher#191]
**Describe the bug**
My experience: As I work in blender, I try to launch a new blender instance using the shortcut, only to realize it doesn't work. I then look at my start bar only to see blender launcher is closed. I look at the tray, I see the icon but it disappears as soon as I mouse over, common behavior when a software has crashed.

Other than that, I can't really tell when Blender Launcher crashes.

Windows 10 Pro 21H1
Blender Launcher 1.15.1
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/9852011/Blender.Launcher.log)

I've attached my log file but it seems what was logged is from 1-2 months ago?

**Comment by xan2622** [comment]
Hi @baronlanteigne.
Could you try with the latest _development version_ of Blender Launcher ? 👉 [link here](https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477)

Note that this "dev build" might be your last chance to get Blender Launcher work since DotBow (its author) has recently mentioned that the development is halted: https://github.com/DotBow/Blender-Launcher/discussions/188

**Comment by SkyNinja** [comment]
I love it when software I've just discovered is abandoned with huge issues that make it nearly unusable.

FWIW, the dev build has the same issue.
