### ISSUE TITLE
The main window reopens every 20 minutes aprox

### ISSUE THREAD

**Issue by tristangrimaux** [DotBow/Blender-Launcher#193]
The main window reopens on its own, in the background, at an unpredictable rate. This is a minor non important issue, but is really annoying. I end up quitting the app when it could comfortably sit in the tray icon without disturbing, announcing whenever there's a new release.

**To Reproduce**
1. Open the app
2. Close the main window
3. wait until it reappears disturbing the Z order of your windows
4. in the background.

**Expected behavior**
Stay closed

**System (please complete the following information):**
 - Operation system: KDE Neon
 - Blender Launcher version: 1.5.1
 - Log file: the log is not showing anything special

**Comment by xan2622** [comment]
Hi @tristangrimaux 
Does it still crash with the latest _development version_ of Blender Launcher ? 👉 [link here](https://github.com/DotBow/Blender-Launcher/discussions/163#discussioncomment-3530477)

Note that there won't be new versions of Blender Launcher anytime soon since DotBow (its author) has recently mentioned that the development is halted: https://github.com/DotBow/Blender-Launcher/discussions/188
