### ISSUE TITLE
Please host your service on your own server instead of pointing to blender.org

### ISSUE THREAD

**Issue by mcgrathd** [DotBow/Blender-Launcher#213]
Hi,

I would kindly ask if you can find an alternate way to have your clients check for updated versions of blender rather than the current approach of sending GET and HEAD requests to blender.org servers.

As it stands now, users of your software are sending requests to the servers with what appears to be a request every 10 minutes, for each user, and for every file that exists of Blender. I believe the same checks were happening for the buildbot builds as well.

Might I suggest that you create an Amazon lamba instance, or perhaps simpler, place a static file online, and have your users query that instead. At the very least, using our mirrors would be better.

In terms of impact, we are generating literal gigabytes every week just from your queries. Should this software gain in popularity, you will literally start to knock blender.org offline!

**Comment by ericwomer** [comment]
Yeah, I believe this project is dead in the water, https://github.com/DotBow/Blender-Launcher/discussions/188 as the developer stated there won't be any new releases to this project. So unless someone else forks this project none of the current or future issues will get fixed.

**Comment by DotBow** [comment]
> Hi,
> 
> I would kindly ask if you can find an alternate way to have your clients check for updated versions of blender rather than the current approach of sending GET and HEAD requests to blender.org servers.
> 
> As it stands now, users of your software are sending requests to the servers with what appears to be a request every 10 minutes, for each user, and for every file that exists of Blender. I believe the same checks were happening for the buildbot builds as well.
> 
> Might I suggest that you create an Amazon lamba instance, or perhaps simpler, place a static file online, and have your users query that instead. At the very least, using our mirrors would be better.
> 
> In terms of impact, we are generating literal gigabytes every week just from your queries. Should this software gain in popularity, you will literally start to knock blender.org offline!

Hi. 
While this request sounds fair and logical, it also almost impossible for an individual on a free base.

BL is only getting an html page once per 10 min, didn't know it can have such am impact.

Anyway, if it is giving you troubles the only thing I can suggest is to entirely block BL requests and effectively destroy and shut down almost dead project.

**Comment by ericwomer** [comment]
Every 10 mins is kinda overkill, the only branch that that could be used for is the development branch, and they don't put a new one out every 10 mins. And you could have it manually set to something like every 2 hours depending on which time zone they are in, like have a set inverval at something like 6, 12, 6, 12 but have it to where its going off of a local time zone. 

On a side note, how did you get past the issues where every / was for float and not using // instead for int, I get a lot of errors when running a custom built BL complaining about a float passed instead of the needed int.

**Comment by ericwomer** [comment]
On a side note, is the list of available downloadable versions of blender cached or is it a fresh download every time you load up and select the Download tab?

**Comment by xan2622** [comment]
> Anyway, if it is giving you troubles the only thing I can suggest is to entirely block BL requests and effectively destroy and shut down almost dead project.

Please don't make *Blender Launcher* die. It is a very convenient utility. 

> As it stands now, users of your software are sending requests to the servers with what appears to be a request every 10 minutes, for each user, and for every file that exists of Blender. I believe the same checks were happening for the buildbot builds as well.
In terms of impact, we are generating literal gigabytes every week just from your queries. Should this software gain in popularity, you will literally start to knock blender.org offline!

To make things easier for the Blender.org servers, maybe *Blender Launcher* could just check for new Blender versions only once right after *Blender Launcher* is ran and only once a day? 

Example: 
- Monday, 05:30pm: the user launches *BL* for the first time of the day. *BL* checks for new versions of Blender builds.
- Monday, 05:31pm: the user then launches Blender thanks to *BL* and uses Blender for ~10 minutes then closes Blender and *BL*.
- Monday, 06:00pm: the user launches *BL* a second time but this time, *BL* doesn't check for new builds anymore because it already did it earlier the same day.

Would it be enough to keep Blender.org servers safe ?

**Comment by mcgrathd** [comment]
I personally understand the desire to have the latest and greatest Blender version, the instant it is released, but feel this tool is possibly an unnecessary use of resources and, perhaps more importantly, developer talent. While there is clearly interest for this type of product, it may be more beneficial to polish such a design in a scalable and efficient way, and submit it as part of Blender itself, rather than remain a 3rd party tool.

Take all of the available ways to download and check for Blender updates. We have the Microsoft store, Ubuntu systems have snap, and possibly Ubuntu PPA's. Finally you have Steam which will even let you pick a version to pin to. These are excellent and trusted ways to receive files from Blender, including signed files in certain cases. With a 3rd party tool, an external developer is ultimately in charge of where they send users, and could change this with a mere update. Not very ideal, to say the least.

Finally, let's not forget that If a user is actively looking to test for bugs, they can grab a copy of a development build from builder.blender.org, and do so, at their leisure. While most users that are deep into bug reporting and testing tend to use their own development environment, a tool like this is eventually going to rot away in a users system tray of less focused users, forever doomed to phone home to the blender servers and remain outside of the control of the administration, with no ability to stop it should the user base and queries become excessive, as they are starting to.

Take care! o/

**Comment by xan2622** [comment]
> I personally understand the desire to have the latest and greatest Blender version, the instant it is released

*Blender Launcher* is not just a tool to get the latest versions of Blender asap. It also allows the user to easily install several portable versions of Blender side-by-side. This is a great feature because the latest version of Blender can sometimes make add-ons not compatible anymore: 
- The user can this way keep using an old version of Blender (to continue using an old add-on) while being able to try the latest features that Blender brings in its latest build, in another installation. 
- Add-ons developers also sometimes want to have several Blender installations, to test and update their add-ons.

It's not implemented yet (I hope it will be one day) but the way *Blender Launcher* works, and [thanks to this suggestion](https://github.com/DotBow/Blender-Launcher/issues/207), it might soon become easier to copy+paste settings from a (previous) Blender installation to another one (sometimes Blender users miss the opportunity to reuse old settings on the splashscreen that appears after launching a new version of Blender). This feature, if it is implemented one day, will certainly help many Blender users in this regard.

---

> While there is clearly interest for this type of product, it may be more beneficial to polish such a design in a scalable and efficient way, and submit it as part of Blender itself, rather than remain a 3rd party tool.

I would also like to see an "updater system" implemented in Blender itself (if this is what you meant) but it is not just what *Blender Launcher* is, as explained in my previous paragraph. 

Btw, there are many frameworks/libraries that could help implementing this feature: 
https://winsparkle.org/
https://sparkle-project.org/
https://github.com/google/omaha
https://github.com/Squirrel/Squirrel.Windows
https://github.com/ravibpatel/AutoUpdater.NET
https://wyday.com/wyupdate/
... but it's not given to anyone to know C/C++ enough to implement such an updater in Blender itself.

Btw, the different ways to download or update Blender (that you mentioned in your message: Microsoft Store, Steam, ...) seem to imply that the Blender Developers have preferred these solutions rather implementing an auto-updater directly inside Blender.

---

> With a 3rd party tool, an external developer is ultimately in charge of where they send users, and could change this with a mere update. Not very ideal, to say the least.

This is true. This is why I asked DotBow not to erase the downloaded ZIPs in the Temp folder, [to let users compare the SHA256 files](https://github.com/DotBow/Blender-Launcher/issues/133).

---

> a tool like this is eventually going to rot away in a users system tray of less focused users, forever doomed to phone home to the blender servers and remain outside of the control of the administration, with no ability to stop it should the user base and queries become excessive, as they are starting to.

If your main concern is not to make Blender.org servers crawl to the load (which, I wouldn't want either), maybe DotBow can change the frequency of update checks, as suggested earlier by [ericwomer](https://github.com/DotBow/Blender-Launcher/issues/213#issuecomment-1407475873) and [me](https://github.com/DotBow/Blender-Launcher/issues/213#issuecomment-1407521748) but also by using Blender download mirrors, as you suggested.

Or maybe another idea (not to add extra load on Blender download servers): 
- Remove the option, in *Blender Launcher*, to check for new builds automatically at a given frequency. And just let the user manually check for new builds with the "Check" button at the bottom-left corner of the BL UI, but only allowing it once a day.

**Comment by izzy** [comment]
@mcgrathd given you seem to know some stuff about the internals, is there any API one could query to get a list of releases?

I'm looking into forking/fixing this(or just outright building an alternative version) but I'm not too happy about how this project just does it via web scraping without any caching etc. I mean, when you get the whole HTML every ten minutes with a few thousand or even million people, that's not just a resource waste for you, that's a resource waste in general. 

The points made about availability in stores are good, but I think lots of people use this tool for lots of different reasons(I for myself simply need a few different versions and the tool makes that convenient) and its existence is very much valid, so I'd rather build something that works well for everyone while also having less impact on everyone involved in general.

If there is no such API I'll probably go through scrape+convert and deliver people a cached file, but I'd rather not do that given the maintainability of scraper code is always an adventure in itself.

**Comment by thinsoldier** [comment]
Was anything ever done regarding this issue? I personally don't need it to check for new builds more than once every 48 hours. Defaulting to 500 or 1000 minutes instead of 10 should help a lot.

**Comment by xan2622** [comment]
I used to like the option to change the "check frequency" value in the Options but if it has a bad impact on the Blender servers, I think it should be removed from Blender Launcher asap.

Instead of allowing the user to type a "check frequency" in minutes, Blender Launcher should only allow "hours", with a minimum interval of 24 hours between two checks (24 hours being the minimum default value).
