### ISSUE TITLE
List previously addons when adding new Blender installation

### ISSUE THREAD

**Issue by Ansraer** [DotBow/Blender-Launcher#218]
**Is your feature request related to a problem? Please describe.**
I am using a number of add-ons, and have run into problems in the past when I opened a project without one of them.
Whenever I update my blender version I have to make sure I don't forget any of them.

**Describe the solution you'd like**
When you install a new blender version a popup should open that shows you all third-party extensions you had installed in your previous blender version. This way I could make sure that I don't forget about any extension when updating.

**Describe alternatives you've considered**
I considered some kind of auto installation, but sadly not all my addons can be found on any single source (such as the blender market). Plus, some add-ons require the installation of third-party apps (e.g. UVPacker), so automation is almost impossible.

**Comment by xan2622** [comment]
Hi. 
You don't need *Blender Launcher* for that. 
You can create a list of your previous add-ons with a Python script:

1. In Blender, go to the "Scripting" tab (at the top)
2. Split the Interface in two areas, in order to display two Text Editors
3. In the Text Editor at the top, create a new Python script file (for example, named "*Generate_Addons_List.py*")
4. And paste this code: 
```
import bpy 

with open('d:/Blender_Addons_List.txt', 'a') as file:

    for addon in bpy.context.preferences.addons[:]:
        file.write(addon.module + '\n')
```
5. If you run this script, it will create a file named "*d:/Blender_Addons_List.txt*". 
6. Then, you can load this "*d:/Blender_Addons_List.txt*" file in the other Text Editor.

You can run this script whenever you want, for example, before upgrading to a new version of Blender.
