### ISSUE TITLE
Being able to associate .blend files with Blender Launcher

### ISSUE THREAD

**Issue by Sasson100** [DotBow/Blender-Launcher#219]
Problem: It's annoying that if I want to open a .blend file that I downloaded from somewhere when I use blender launcher, I have to open blender launcher, open a build, then try to find the file in Blender, and if I do associate .blend files with Blender Launcher, after I choose a build, I need to find the file again inside of Blender

Solution: Let us associate .blend files with Blender Launcher in a way where if we open a .blend file, it takes us to blender launcher, and when we choose a build, it automatically opens the file that we selected in the first place, instead of then having to find it again inside Blender.

I couldn't really think of any other ways to make it, how I imagine it, it should be like how it is if we associate .blend files with normal Blender, but with the extra step of choosing a build.

**Comment by Barina** [comment]
+1 for that!

This may require to cache your projects. lets say in additional tab besides the "Library" tab. similar to Unity's Hub.
It's also possible to get the version of Blender a project has been saved with from the blend file, so when double clicking a .blend file, the launcher can detect that already on the first time (similar to what is suggested in #217) and if that version doesn't installed already, a popup will ask what to do (install that version before open or just open (up\downgrade) with another installed version)

**Comment by thinsoldier** [comment]
You could just drag and drop the desired file into Blender.

**Comment by MagnumVD** [comment]
Got the same request because I often want to check .blend files quickly from my windows file manager. It's tedious to have to open up the .blend files from the blender instance separately

What I currently do is have the blender launcher opened when opening a .blend file, that's least a bit more convenient

Other idea I had would be that the blender launcher uses the blender version assigned to quick launch
Best thing would be if you could select your desired way of opening up a .blend file in the settings tab

**Comment by DotBow** [comment]
Hi!

You can associate .blend files with preferred build using context menu -> register extension.

**Comment by xan2622** [comment]
Just a side note about how Blender will manage File Registration on Windows : 
https://projects.blender.org/blender/blender/pulls/107013
