### ISSUE TITLE
this platform is not supported error on linux.

### ISSUE THREAD

**Issue by amiroo54** [DotBow/Blender-Launcher#222]
**Describe the bug**
Blender Launcher dosn't open when running it through bash terminal. 

**To Reproduce**
1. Navigate to Blender Launcher Location
2. Run './Blender Launcher' in terminal

**Expected behavior**
Blender Launcher Oppening.

**System (please complete the following information):**
 - Operation system: Linux Ubuntu 22.10
 - Blender Launcher version: Latest (idk the version).
[Blender Launcher.log](https://github.com/DotBow/Blender-Launcher/files/11009348/Blender.Launcher.log)

**Comment by johnyc90** [comment]
Hi @amiroo54. I've faced a similar issue as yours described here: #174 
Long story short: the issue seems to originate with the use of Wayland. Whatever is the library/version used to draw the interface, it does not seem to support Wayland yet. You can easily work around this by switching back to Xorg for the time being (selectable in the log in screen).
