### ISSUE TITLE
Press "Check" button but always show " No new builds available"

### ISSUE THREAD

**Issue by EricWood15** [DotBow/Blender-Launcher#248]
**Press "Check" button but always show " No new builds available"**

the network should be ok, but never get builds.

![blender launcher bug](https://github.com/DotBow/Blender-Launcher/assets/61120872/2438426d-9ed7-49a6-b4cc-723bcb12bf2f)

**Comment by MMDPrh** [comment]
I first thought I was the only one who had this problem, but when I looked up into this problem, seems like after the Blender website got attacked and turned back on, the api and the addresses that the blender launcher always get the builds from it had changed... and now it shows "No new builds available, and since the last release was 2022 and the developer isn't here, we can no longer use the download function, however we can still download manually and load them into app, but we cant use the app properly anymore... that's really sad I loved this launcher

**Comment by Victor-IX** [comment]
https://github.com/Victor-IX/Blender-Launcher/releases
This fork version fixes the Daily and Experimental build. we currently have a problem with Stables ones, the web request is currently blocked by the Blender foundation, I contacted them, and they are working on a solution on their side so a fix for that will be available soon
