### ISSUE TITLE
Blender launcher totaly blank upon start, fresh install on win 10

### ISSUE THREAD

**Issue by nerba** [DotBow/Blender-Launcher#40]
**Describe the bug**
Blender Launcher is blank. Screenshot shows the log, my blender folder and Blender Launcher totally blank for some reason.

**To Reproduce**
1. Start it
2. BL is blank
3. Screenshot attached

**Screenshots**
![blender-launcher](https://user-images.githubusercontent.com/60974208/101507785-3a7b9080-3977-11eb-9b12-bb5311bed9df.png)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 2.90
 - Log file: visible on screenshot

**Comment by DotBow** [comment]
Hi!

This issue happened because you choose [UAC protected directory](https://github.com/DotBow/Blender-Launcher/wiki/Installation#windows-users) as Library Folder.
This issue is already handled in upcoming 1.9.0 version.

You can wait until it (probably this weekends) or fix it via editing registry for now:
1. Quit BL or kill via task manager
1. Press WIN+R
1. Run "regedit"
1. Search for "blender_launcher" and delete "library_folder" value

![изображение](https://user-images.githubusercontent.com/32243930/101540853-ab3f9e80-39b1-11eb-8caa-43ad8acb2977.png)

1. Start BL again and choose new Library Folder (on a non system drive is the best)

Sorry tho this troubles 😞

**Comment by DotBow** [comment]
Hi!
Latest release contain proper check for writing permissions, so please update
https://github.com/DotBow/Blender-Launcher/releases/tag/v1.9.0
