### ISSUE TITLE
Ability to create a shortcut for launching currently assigned as QuickLaunch build.

### ISSUE THREAD

**Issue by qbicksan** [DotBow/Blender-Launcher#81]
Or maybe there is a way of making such a shortcut already?
I personally have an ultrawide monitor and it is quite uncomfortable to middle click on tiny icon in system tray.
Just a shortcut with such a command would be more than welcomed.

**Comment by DotBow** [comment]
Hi!
I think you can achieve this using [autohotkey](https://www.autohotkey.com/)...
I will look into how it can be done via python.

**Comment by nuzzar** [comment]
@qbicksan Are you on Windows 10? I use Win+S all the time for that. Also Blender Launcher has a shortcut feature already unfortunately it puts the shortcut on the desktop instead of AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Blender folder. Because of this Windows will not adapt to how many times you use Blender. So you have to type 'Win+S' and 'Blender' to open it instead of 'Win+S' and 'B' if you use blender a lot.

@DotBow Is it possible to put the shortcut in the start menu just like regular Blender? This will make Windows to adapt and make it blender easier to find on Windows Search.

**Comment by DotBow** [comment]
Global shortcut feature added in 1.14.0
Please, create a separate ticket for other requests/issues.
